---
name: idr0149-batty-sisterchromatids/experimentE
version: 1

defaults:
  include: false
  type: string
  split:
  includeclient: true
  visible: true
  omitempty: true

columns:

  - name: Characteristics [Cell Cycle Phase]
    clientname: Cell Cycle Phase
    include: true

  - name: Experimental Condition [Sister Chromatid Labelling]
    clientname: Sister Chromatid Labelling
    include: true

  - name: Experimental Condition [Genome Editing]
    clientname: Genome Editing
    include: true

  - name: Channels
    clientname: Channels
    include: true


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/cell_line
      columns:
        - name: Characteristics [Cell Line]
          clientname: Cell Line
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/cell_line/supplementary
      columns:
      - name: Comment [Cell Line]
        clientname: Cell Line Comment
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
        - name: Comment [Gene Identifier 1]
          clientname: Gene Identifier
          include: true
        - name: Comment [Gene Identifier 1]
          clientname: Gene Identifier URL
          clientvalue: >
                http://www.ensembl.org/id/{{ value|urlencode }}
          include: true
        - name: Comment [Gene Symbol 1]
          clientname: Gene Symbol
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
        - name: Comment [Gene Identifier 2]
          clientname: Gene Identifier
          include: true
        - name: Comment [Gene Identifier 2]
          clientname: Gene Identifier URL
          clientvalue: >
              http://www.ensembl.org/id/{{ value|urlencode }}
          include: true
        - name: Comment [Gene Symbol 2]
          clientname: Gene Symbol
          include: true


advanced:
  ignore_missing_primary_key: true
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/cell_line
      keys:
        - Cell Line
    - namespace: openmicroscopy.org/mapr/gene
      keys:
        - Gene Identifier
        - Gene Symbol
